import { useState, useEffect, useRef, useCallback } from 'react';

const RAG_BASE_URL = import.meta.env.VITE_RAG_API_BASE_URL ?? 'http://localhost:9000';
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:5000';

/**
 * Production-grade helper to fetch the latest Pakistani Urdu speech.mp3 audio
 * generated by generatePkVoice on the backend / RAG server.
 * Retries with exponential backoff while background TTS is writing the audio file.
 */
async function fetchAudioBlobWithRetry(primaryUrl, fallbackUrl, isCancelled, { maxRetries = 10, initialDelayMs = 1000, baseDelayMs = 1200 } = {}) {
    if (initialDelayMs > 0) {
        await new Promise(r => setTimeout(r, initialDelayMs));
    }

    let lastError = null;
    const urlsToTry = [primaryUrl, fallbackUrl].filter(Boolean);

    for (let attempt = 0; attempt <= maxRetries; attempt++) {
        if (isCancelled()) {
            throw new Error('Playback cancelled by user');
        }

        for (const baseUrl of urlsToTry) {
            try {
                // Cache-busting URL so browser always fetches latest generated speech.mp3
                const timestampedUrl = baseUrl.includes('?') 
                    ? `${baseUrl}&_t=${Date.now()}` 
                    : `${baseUrl}?_t=${Date.now()}`;

                const response = await fetch(timestampedUrl, {
                    method: 'GET',
                    cache: 'no-store',
                    headers: { 'Accept': 'audio/mpeg, audio/*' }
                });

                if (!response.ok) {
                    throw new Error(`HTTP ${response.status}`);
                }

                const blob = await response.blob();

                // Valid Urdu MP3 audio files generated by UpliftAI are > 2KB. Empty or partial files are tiny.
                if (blob.size < 2000) {
                    throw new Error(`Audio file still generating (${blob.size} bytes)`);
                }

                return URL.createObjectURL(blob);
            } catch (err) {
                lastError = err;
            }
        }

        if (attempt < maxRetries) {
            if (isCancelled()) throw new Error('Playback cancelled by user');
            const delay = baseDelayMs * Math.pow(1.15, attempt);
            await new Promise(r => setTimeout(r, delay));
        }
    }

    throw new Error(`Failed to load speech MP3 after ${maxRetries + 1} attempts: ${lastError?.message}`);
}

export default function useSpeechSynthesis({ onStart, onEnd, onError } = {}) {
    const [isSpeaking, setIsSpeaking] = useState(false);
    const [error, setError] = useState('');
    const audioRef = useRef(null);
    const blobUrlRef = useRef(null);
    const cancelledRef = useRef(false);

    const releaseBlobUrl = () => {
        if (blobUrlRef.current) {
            try {
                URL.revokeObjectURL(blobUrlRef.current);
            } catch (e) {
                // Ignore cleanup errors
            }
            blobUrlRef.current = null;
        }
    };

    const cancel = useCallback(() => {
        cancelledRef.current = true;
        if (audioRef.current) {
            try {
                audioRef.current.pause();
                audioRef.current.currentTime = 0;
                audioRef.current.src = '';
            } catch (e) {
                // Ignore pause errors
            }
            audioRef.current = null;
        }
        releaseBlobUrl();
        setIsSpeaking(false);
    }, []);

    /**
     * speak(audioUrl)
     * Fetches and plays the Pakistani Urdu speech.mp3 file generated by generatePkVoice.
     * Completely uses HTML5 Audio with MP3 files from backend, bypassing browser SpeechSynthesis.
     */
    const speak = useCallback(async (audioUrl) => {
        cancel();
        cancelledRef.current = false;

        // Determine primary URL candidate
        let primaryUrl = audioUrl;
        if (!primaryUrl || typeof primaryUrl !== 'string' || !primaryUrl.trim()) {
            primaryUrl = `${RAG_BASE_URL}/speech.mp3`;
        } else if (!/^https?:\/\//i.test(primaryUrl)) {
            primaryUrl = `${RAG_BASE_URL}${primaryUrl.startsWith('/') ? '' : '/'}${primaryUrl}`;
        }

        const fallbackUrl = `${API_BASE_URL}/speech.mp3`;

        try {
            console.log(`[AudioPlayer] Fetching Pakistani Urdu MP3 from: ${primaryUrl}`);

            const objectUrl = await fetchAudioBlobWithRetry(
                primaryUrl,
                fallbackUrl,
                () => cancelledRef.current
            );

            if (cancelledRef.current) {
                try { URL.revokeObjectURL(objectUrl); } catch (e) {}
                return;
            }

            blobUrlRef.current = objectUrl;
            const audio = new Audio(objectUrl);
            audioRef.current = audio;

            audio.onplay = () => {
                if (cancelledRef.current) return;
                setIsSpeaking(true);
                setError('');
                if (onStart) onStart();
            };

            audio.onended = () => {
                setIsSpeaking(false);
                audioRef.current = null;
                releaseBlobUrl();
                if (onEnd) onEnd();
            };

            audio.onerror = (e) => {
                console.error('[AudioPlayer] Audio playback error:', e);
                setIsSpeaking(false);
                audioRef.current = null;
                releaseBlobUrl();
                if (!cancelledRef.current) {
                    setError('Urdu audio playback error');
                    if (onError) onError('Urdu audio playback failed.');
                }
            };

            const playPromise = audio.play();
            if (playPromise !== undefined) {
                await playPromise.catch((err) => {
                    if (cancelledRef.current) return;
                    console.warn('[AudioPlayer] audio.play() rejected (autoplay restricted or interrupted):', err.message);
                    setIsSpeaking(false);
                    audioRef.current = null;
                    releaseBlobUrl();
                    if (onEnd) onEnd();
                });
            }

        } catch (err) {
            if (cancelledRef.current) return;
            console.warn('[AudioPlayer] Could not fetch Urdu speech MP3:', err.message);
            setIsSpeaking(false);
            if (onEnd) onEnd();
        }
    }, [cancel, onStart, onEnd, onError]);

    useEffect(() => {
        return () => {
            cancel();
        };
    }, [cancel]);

    return {
        isSpeaking,
        error,
        speak,
        cancel,
        isSupported: true
    };
}
