import { useState, useEffect, useRef, useCallback } from 'react';

const RAG_BASE_URL = import.meta.env.VITE_RAG_API_BASE_URL ?? 'http://localhost:9000';
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:5000';
const RAG_WS_URL = import.meta.env.VITE_RAG_WS_URL ?? 'ws://localhost:9000';

/**
 * Production-grade helper to fetch and play a specific Pakistani Urdu speech MP3 audio
 * generated by generatePkVoice on the RAG server.
 * The RAG /chat endpoint now awaits TTS completion before responding, so the audio
 * file should already exist. Retries are kept as a safety net for network hiccups.
 */
async function fetchAudioBlobWithRetry(audioUrl, isCancelled, { maxRetries = 6, initialDelayMs = 0, baseDelayMs = 500 } = {}) {
    if (initialDelayMs > 0) {
        await new Promise(r => setTimeout(r, initialDelayMs));
    }

    let lastError = null;

    for (let attempt = 0; attempt <= maxRetries; attempt++) {
        if (isCancelled()) {
            throw new Error('Playback cancelled by user');
        }

        try {
            // Cache-busting URL so browser always fetches latest generated speech MP3
            const timestampedUrl = audioUrl.includes('?')
                ? `${audioUrl}&_t=${Date.now()}`
                : `${audioUrl}?_t=${Date.now()}`;

            const response = await fetch(timestampedUrl, {
                method: 'GET',
                cache: 'no-store',
                headers: { 'Accept': 'audio/mpeg, audio/*' }
            });

            if (!response.ok) {
                throw new Error(`HTTP ${response.status}`);
            }

            const blob = await response.blob();

            // Valid Urdu MP3 audio files generated by UpliftAI are > 2KB.
            if (blob.size < 2000) {
                throw new Error(`Audio file too small (${blob.size} bytes)`);
            }

            return URL.createObjectURL(blob);
        } catch (err) {
            lastError = err;
        }

        if (attempt < maxRetries) {
            if (isCancelled()) throw new Error('Playback cancelled by user');
            // Short delay — audio should already be ready; retries are just a safety net
            const delay = Math.min(baseDelayMs * Math.pow(1.3, attempt), 2000);
            await new Promise(r => setTimeout(r, delay));
        }
    }

    throw new Error(`Failed to load speech MP3 after ${maxRetries + 1} attempts: ${lastError?.message}`);
}


export default function useSpeechSynthesis({ onStart, onEnd, onError } = {}) {
    const [isSpeaking, setIsSpeaking] = useState(false);
    const [error, setError] = useState('');
    const audioRef = useRef(null);
    const blobUrlRef = useRef(null);
    const cancelledRef = useRef(false);

    const releaseBlobUrl = () => {
        if (blobUrlRef.current) {
            try {
                URL.revokeObjectURL(blobUrlRef.current);
            } catch (e) {
                // Ignore cleanup errors
            }
            blobUrlRef.current = null;
        }
    };

    const cancel = useCallback(() => {
        cancelledRef.current = true;
        if (audioRef.current) {
            try {
                audioRef.current.pause();
                audioRef.current.currentTime = 0;
                audioRef.current.src = '';
            } catch (e) {
                // Ignore pause errors
            }
            audioRef.current = null;
        }
        releaseBlobUrl();
        setIsSpeaking(false);
    }, []);

    /**
     * speak(audioUrl)
     * Fetches and plays the per-request Pakistani Urdu speech MP3 file generated by generatePkVoice.
     * Uses HTML5 Audio with MP3 files from backend. No static fallback — each call uses
     * the exact URL for the specific query's audio to avoid stale/mismatched audio.
     */
    const speak = useCallback(async (audioUrl) => {
        cancel();
        cancelledRef.current = false;

        // Resolve the final URL — must be a valid per-request audio URL
        let resolvedUrl = audioUrl;
        if (!resolvedUrl || typeof resolvedUrl !== 'string' || !resolvedUrl.trim()) {
            console.warn('[AudioPlayer] No audioUrl provided — skipping playback.');
            if (onEnd) onEnd();
            return;
        }
        // If relative path, prepend RAG base URL
        if (!/^https?:\/\//i.test(resolvedUrl)) {
            resolvedUrl = `${RAG_BASE_URL}${resolvedUrl.startsWith('/') ? '' : '/'}${resolvedUrl}`;
        }

        try {
            console.log(`[AudioPlayer] Fetching Pakistani Urdu MP3 from: ${resolvedUrl}`);

            const objectUrl = await fetchAudioBlobWithRetry(
                resolvedUrl,
                () => cancelledRef.current
            );

            if (cancelledRef.current) {
                try { URL.revokeObjectURL(objectUrl); } catch (e) { }
                return;
            }

            blobUrlRef.current = objectUrl;
            const audio = new Audio(objectUrl);
            audioRef.current = audio;

            audio.onplay = () => {
                if (cancelledRef.current) return;
                setIsSpeaking(true);
                setError('');
                if (onStart) onStart();
            };

            audio.onended = () => {
                setIsSpeaking(false);
                audioRef.current = null;
                releaseBlobUrl();
                if (onEnd) onEnd();
            };

            audio.onerror = (e) => {
                console.error('[AudioPlayer] Audio playback error:', e);
                setIsSpeaking(false);
                audioRef.current = null;
                releaseBlobUrl();
                if (!cancelledRef.current) {
                    setError('Urdu audio playback error');
                    if (onError) onError('Urdu audio playback failed.');
                }
            };

            const playPromise = audio.play();
            if (playPromise !== undefined) {
                await playPromise.catch((err) => {
                    if (cancelledRef.current) return;
                    console.warn('[AudioPlayer] audio.play() rejected (autoplay restricted or interrupted):', err.message);
                    setIsSpeaking(false);
                    audioRef.current = null;
                    releaseBlobUrl();
                    if (onEnd) onEnd();
                });
            }

        } catch (err) {
            if (cancelledRef.current) return;
            console.warn('[AudioPlayer] Could not fetch Urdu speech MP3:', err.message);
            setIsSpeaking(false);
            if (onEnd) onEnd();
        }
    }, [cancel, onStart, onEnd, onError]);


    useEffect(() => {
        return () => {
            cancel();
        };
    }, [cancel]);

    return {
        isSpeaking,
        error,
        speak,
        cancel,
        isSupported: true
    };
}
